#!/usr/bin/env bash
# This script parses the Apache log file to group visitors by IP and HTTP status code, then sorts by the number of occurrences

# Extract IP and HTTP code, sort them, count occurrences, and format output
awk '{print $1, $9}' access.log | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | sort | uniq -c | sort -rn | awk '{printf("%8d %s %s\n", $1, $2, $3)}'

